// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzaOUHUFaHFr6bScQsoI_l0NUXidgH0AY',
    appId: '1:676741507834:web:8df0a4b011378230923743',
    messagingSenderId: '676741507834',
    projectId: 'chatapptute-7739f',
    authDomain: 'chatapptute-7739f.firebaseapp.com',
    storageBucket: 'chatapptute-7739f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlrcTsvwxwTBnHMPlCBnWOUfDj6q77aFU',
    appId: '1:676741507834:android:91558107200aa58d923743',
    messagingSenderId: '676741507834',
    projectId: 'chatapptute-7739f',
    storageBucket: 'chatapptute-7739f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm1zPTy53ae01XOYr-wws-UrsRwv--NOg',
    appId: '1:676741507834:ios:e112d3af60332064923743',
    messagingSenderId: '676741507834',
    projectId: 'chatapptute-7739f',
    storageBucket: 'chatapptute-7739f.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm1zPTy53ae01XOYr-wws-UrsRwv--NOg',
    appId: '1:676741507834:ios:b10c2262da56450e923743',
    messagingSenderId: '676741507834',
    projectId: 'chatapptute-7739f',
    storageBucket: 'chatapptute-7739f.appspot.com',
    iosBundleId: 'com.example.minimalChatApp.RunnerTests',
  );
}
